language: node_js
node_js:
  - '10'
branches:
  only:
    - master
    - develop
    - /issue-*/
env:
  - NODE_ENV=development

before_install:
  - npm cache --force clean
  - npm install -g firebase-tools

script:
  - (cd web; npm install)
  - (cd web; npm run lint && npm run build:dev)

before_deploy:
  - (cd functions; npm install)
  - (cd web; npm run build:dev)

deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_DEVELOP_TOKEN
    project: 'tribedashboard-develop'
    on:
      branch: develop
